version: "3.8"
services:
  vote:
    image: ${DOCKER_REPO}/vote-app:${BUILD_TAG:-latest}
    command: python app.py
    depends_on:
      - redis
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: ${DOCKER_REPO}/result-app:${BUILD_TAG:-latest}
    command: nodemon server.js
    depends_on:
      - db
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: ${DOCKER_REPO}/worker-app:${BUILD_TAG:-latest}
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:5.0-alpine3.10
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
